name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: sanguine-signal-468017-c2
  REGION: us-central1
  SERVICE_NAME: smart-crowd-navigator

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Container
        run: |
          # Use the commit SHA as the image tag for unique identification
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/smart-crowd-navigator:${{ github.sha }}"
          docker build -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/smart-crowd-navigator:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: --allow-unauthenticated
